public without sharing class DSALES_GexCotizacionesHelper {
    //SG Template
    private static final String TEMPLETE_NAME = 'Envi_de_cotizaci_n_1660589806562';
    //GEX
    private static final String GEX_TEMPLATE = 'DSALES_Cotizacion';             // Namrata added
    
    
    private static final String DIRECCION_CORREO = 'atencion@coppel.com';  
    
    @Future(callout=true)
    public static void envioCotizacionGex(String jsonString, String quoteOld){
        try{
            System.debug('>>> response ' + jsonString);
            List<Quote> sObjectList = (List<Quote>) JSON.deserialize(jsonString, List<Quote>.class);
            Map<Id,Quote> mapQuote= (Map<Id,Quote>) JSON.deserialize(quoteOld, Map<Id,Quote>.class);
            Map<String, Account> mapAccount = new Map<String, Account>();
            EmailTemplate templete= new EmailTemplate();
            EmailTemplate templeteGEX= new EmailTemplate();
            OrgWideEmailAddress owa = new OrgWideEmailAddress();
            for(Quote item: sObjectList){
                mapAccount.put(item.AccountId, new Account());  
            }
                for(Account item: [Select Id,Name,PersonContactId, PersonEmail from Account where Id in : mapAccount.keySet() WITH SECURITY_ENFORCED]){
                    mapAccount.put(item.Id, item);
                }
                templete = [Select Id, HtmlValue, Subject, DeveloperName from EmailTemplate Where DeveloperName = :TEMPLETE_NAME WITH SECURITY_ENFORCED];
                system.debug('Template name------->' +templete.DeveloperName);
                templeteGEX = [Select Id, HtmlValue, Subject, DeveloperName from EmailTemplate Where DeveloperName = :GEX_TEMPLATE WITH SECURITY_ENFORCED];     // Namrata added
                system.debug('Template name------->'  +templeteGEX.DeveloperName);
                owa = [Select Id,Address From OrgWideEmailAddress Where Address = :DIRECCION_CORREO WITH SECURITY_ENFORCED LIMIT 1];
            List<Messaging.SingleEmailMessage> messageList = new List<Messaging.SingleEmailMessage>();
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String recordID='';
            for(Quote item: sObjectList){
                system.debug('Id: del Coti: '+item.Id);
                system.debug('Enviar Coti: '+item.DSALES_Enviarcotizacion__c);
                system.debug('Mapa Coti: '+mapQuote.get(item.Id).DSALES_Enviarcotizacion__c);
                if(item.DSALES_Enviarcotizacion__c==true && mapQuote.get(item.Id).DSALES_Enviarcotizacion__c==false)
                {
                    system.debug('Entró');
                    String correo = item.DSALES_Contado__c ? item.DSALES_EmailNew__c : item.Email ;
                    Account acc = mapAccount.get(item.AccountId); 
                    mail.setToAddresses(new string[] {correo});
                    system.debug('Email: '+correo);
                    //  Namrata changes start
                    recordID=item.RecordTypeId;
                    //Namrata changes end
                    mail.setOrgWideEmailAddressId(owa.Id);     
                    Blob b = generarPFD(item.Id); 
                    Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                    efa.setContentType('application/pdf');
                    efa.setInline(False);
                    efa.setFileName('Cotización.pdf');
                    efa.setBody(b);
                    mail.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
                    messageList.add(mail); 
                }
                else
                {
                    system.debug('NO Entró');
                }
            }
            RECORDTYPE motos= [SELECT Id, Name FROM RECORDTYPE WHERE Id=:recordID WITH SECURITY_ENFORCED ];
            if(motos.Name=='Venta de Seguro de Motos'){          
                mail.setHtmlBody(templete.HtmlValue);
                mail.setSubject(templete.Subject);
            }
            else if(motos.Name=='Venta de Garantía Extendida'){
                mail.setHtmlBody(templeteGEX.HtmlValue);
                mail.setSubject(templeteGEX.Subject);
            }  
            if(messageList.Size()!=0)
            {
                Messaging.sendEmail(messageList, false);
            }
            System.debug('Correo enviado');
        }catch(Exception ex){
            System.debug('Error: '+ex.getMessage() + ', Línea: '+ex.getLineNumber());
        }
    }
    
    public static Blob generarPFD(Id quoteId){
        PageReference pdf = Page.Cotizacion; 
        pdf.setRedirect(False);
        pdf.getParameters().put('quoteID',quoteId);
        if (Schema.sObjectType.Quote.isQueryable()&&Schema.sObjectType.Quote.isDeletable()) {
            List<Quote> dupQuote = [SELECT Id, Name,OpportunityId, DSALES_EmailNew__c, Pricebook2Id, RecordTypeId, Status, DSALES_Enviarcotizacion__c, dsalesTienda, dsalesVendedor,
            dsalesFechaDeCreacionPresupuesto, ExpirationDate, DSALES_esClon__c FROM Quote where DSALES_esClon__c= true]; 
            delete dupQuote;
        }
         
        Blob b; 
        if(!test.isRunningTest())
        {
            b = pdf.getContent();
        }  
        else
        {
            b = blob.valueOF('Test');
        }
           
        return b;
    }
    
}