public without sharing class DSALES_UpdateInfoPago {
    /*public static void updateInfoPagoPoliza(List<InsurancePolicy> poliza){
        for(InsurancePolicy p:poliza){
                DSALES_CreateInsurancePolicy.updateInfoPago(p);
        }
    }*/
    /*
    public static void cancelarPoliza(Map<Id,SObject> existingRecords,List<InsurancePolicy> records){
        List<InsurancePolicy> listRecord = (LIst<InsurancePolicy>)records;
        for(InsurancePolicy poliza :listRecord){
            InsurancePolicy policyOld = (InsurancePolicy)existingRecords.get(poliza.Id);
        System.debug('Estatus poliza ant:'+policyOld.DSALES_Estatusdepliza__c);
        System.debug('Estatus poliza desp:'+poliza.DSALES_Estatusdepliza__c);
            if(policyOld.DSALES_Estatusdepliza__c!=poliza.DSALES_Estatusdepliza__c && poliza.DSALES_Estatusdepliza__c=='Cancelada'){
                System.debug('Si hay que cancelar');
                DSALES_CancelacionProductosRequest.cancelarPartidaDeSeguro(poliza);
            }
        }  
       
    }
    */

    
    
}